version: '3.9'
services:
  api:
    build: .
    networks:
      - api
      - internal
  redis:
    image: redis:6-alpine
    networks:
      - internal

networks:
  internal:
    name: ${COMPOSE_PROJECT_NAME}_network
  api:
    name: movies_api_network
